### ISSUE TITLE
Oven Firmware V2 API Update

### ISSUE THREAD

**Issue by huangyq23** [huangyq23/anova-oven-forwarder#1]
Anova is updating the firmware and its backend API

**Comment by bwhitman** [comment]
Yes, my apo updated to 2.0.11 and this code no longer works (no longer prints out the oven status). Do we know what we need to change to get that working?

**Comment by huangyq23** [comment]
Closed in ae11e386a0f9ac7d88cc86546aac4b86c649e4d5

**Comment by bwhitman** [comment]
Nice thanks !!!
