### ISSUE TITLE
Discord link not working

### ISSUE THREAD

**Issue by bogd** [huangyq23/anova-oven-forwarder#6]
"Oops! Unable to accept invite!" when attempting to open the discord invite link from README.md

**Comment by huangyq23** [comment]
Try this: https://discord.gg/pgWaAHEjhS

**Comment by bogd** [comment]
Same issue - "Whoops... Unable to accept invite!" :(

**Comment by huangyq23** [comment]
@bogd 
That's weird. Not sure why you can't accept the invite. I have confirmed links are indeed not expired. I am new to Discord as well so I would appreciate if you can help me troubleshoot.
<img width="765" alt="image" src="https://github.com/huangyq23/anova-oven-forwarder/assets/198561/d638d856-fd73-4ea7-aea8-a33eb6a028fb">
