### ISSUE TITLE
/airFry endpoint documentation?

### ISSUE THREAD

**Issue by bogd** [huangyq23/anova-oven-forwarder#7]
The README file mentions an `/airFry` endpoint for the Koa app. However, I can find no additional documentation regarding the endpoint, and no reference to it in the source code.

I am trying to figure out the syntax of the "start cook" oven command, so that I can actually send commands to the oven. 

Can you point me in the right direction?

**Comment by bogd** [comment]
After taking a closer look at the code, it apppears that the `/airFry` endpoint was removed when the code was updated to support the new (let's call it "v2") Anova API.

**Comment by huangyq23** [comment]
I removed it temporarily when refactoring for V2 protocol support.

It is still possible to issue commands though the Anova API, but I need to think about the best interface to expose all the combinations of the oven functionality consistently. Especially with how to handle multi-cook and timers correctly.

I'd love to learn more about your use case though!

**Comment by bogd** [comment]
For now, my use case is simply automating a preheat sequence :) .

I have attempted to document my findings about the API in [my own repo](https://github.com/bogd/anova-oven-api). Including the fact that this seems to be a unified API, for both sous-vide cookers and ovens. 

My hope is that I will be able to find someone who can help me turn this into a full-fledged HomeAssistant integration. Which would move many of the complex stuff (influxdb integration, exposing the additional functionality, etc) into the corresponding parts of HAss.

For now, though, I have a small client (in the same repo) that works well enough for my use case. So we can close this issue - I asked about the endpoint, found out why it was not working, problem solved :)

If you fix the Discord link in your repo, I would gladly continue the discussion there. 

Thank you for your reply!
